
exports.seed = function(knex) {
  // Deletes ALL existing entries

      return knex('sub_category').insert([
        {
          sub_category_name:"Animal Products",
          category_id:1
        },
        {
          sub_category_name:"Animal Products - Other",
          category_id:1
        },
        {
          sub_category_name:"Livestock",
          category_id:1
        },
        {
          sub_category_name:"Poultry",
          category_id:1
        },
        {
          sub_category_name:"Beans",
          category_id:2
        },
        {
          sub_category_name:"Barley",
          category_id:3
        },
        {
          sub_category_name:"Maize",
          category_id:3
        },
        {
          sub_category_name:"Millet",
          category_id:3
        },
        {
          sub_category_name:"Rice",
          category_id:3
        },
        {
          sub_category_name:"Sorghum",
          category_id:3
        },
        {
          sub_category_name:"Wheat",
          category_id:3
        },
        {
          sub_category_name:"Fruits",
          category_id:4
        },
        {
          sub_category_name:"Coffee",
          category_id:5
        },
        {
          sub_category_name:"Tea",
          category_id:5
        },
        {
          sub_category_name:"Tobacco",
          category_id:5
        },
        {
          sub_category_name:"Vanilla",
          category_id:5
        },
        {
          sub_category_name:"Peas",
          category_id:6
        },
        {
          sub_category_name:"Cassava",
          category_id:7
        },
        {
          sub_category_name:"Potatoes",
          category_id:7
        },
        {
          sub_category_name:"Nuts",
          category_id:8
        },
        {
          sub_category_name:"Sunflowers",
          category_id:8
        },
        {
          sub_category_name:"Brinjals",
          category_id:9
        },
        {
          sub_category_name:"Cabbages",
          category_id:9
        },
        {
          sub_category_name:"Carrots",
          category_id:9
        },
        {
          sub_category_name:"Cauliflower",
          category_id:9
        },
        {
          sub_category_name:"Chillies",
          category_id:9
        },
        {
          sub_category_name:"Cucumber",
          category_id:9
        },
        {
          sub_category_name:"Ginger",
          category_id:9
        },
        {
          sub_category_name:"Kales",
          category_id:9
        },
        {
          sub_category_name:"Lettuce",
          category_id:9
        },
        {
          sub_category_name:"Onions",
          category_id:9
        },
        {
          sub_category_name:"Tomatoes",
          category_id:9
        }
        
      ]);
}
